# Copyright (C) 2024 Openwrt.org
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for NginxManager
LUCI_DEPENDS:=+luci-nginx +luci-ssl-nginx +luci-ssl-openssl +luci-compat
LUCI_PKGARCH:=all
PKG_VERSION:=1.0
PKG_RELEASE:=20211030
PKG_MAINTAINER:=axing

include $(TOPDIR)/feeds/luci/luci.mk
